**DAY - 1**

In [1]:
import pandas as pd

sheets= [
    'hotels',
    'cities',
    'daily_finance',
    'bookings',
    'campaigns',
    ]

In [2]:
for sheet in sheets:
    globals()["df_"+ sheet] = pd.read_excel('hotel_chain_eda_practice.xlsx', sheet_name=sheet)

In [3]:
print(df_hotels.shape)
df_hotels.index

(8, 7)

RangeIndex(start=0, stop=8, step=1)

In [4]:
df_campaigns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    6 non-null      int64
 1   city_id        6 non-null      int64
 2   campaign_name  6 non-null      object
 3   start_date     6 non-null      datetime64[ns]
 4   end_date       6 non-null      datetime64[ns]
 5   budget_gbp     6 non-null      int64
 6   channel        6 non-null      object
dtypes: datetime64[ns](2), int64(3), object(2)
memory usage: 468.0+ bytes

In [5]:
df_cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city_id     8 non-null      int64
 1   city        8 non-null      object
 2   region      8 non-null      object
 3   country     8 non-null      object
 4   population  8 non-null      int64
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes

In [6]:
df_daily_finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                719 non-null    datetime64[ns]
 1   hotel_id            722 non-null    int64
 2   revenue_gbp         718 non-null    float64
 3   room_revenue_gbp    722 non-null    float64
 4   food_revenue_gbp    722 non-null    float64
 5   operating_cost_gbp  720 non-null    float64
 6   occupancy_pct       722 non-null    float64
 7   rating              719 non-null    float64
 8   notes               360 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 50.9+ KB

In [7]:
df_bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   booking_id     1001 non-null   int64
 1   hotel_id       1001 non-null   int64
 2   booking_date   1001 non-null   datetime64[ns]
 3   check_in_date  1001 non-null   datetime64[ns]
 4   room_nights    1000 non-null   float64
 5   guests         1001 non-null   int64
 6   channel        1001 non-null   object
 7   status         1001 non-null   object
 8   amount_gbp     1000 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(3), object(2)
memory usage: 70.5+ KB

In [8]:
df_hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hotel_id     8 non-null      int64
 1   hotel_name   8 non-null      object
 2   city_id      8 non-null      int64
 3   category     8 non-null      object
 4   rooms        8 non-null      int64
 5   opened_date  8 non-null      datetime64[ns]
 6   manager      8 non-null      object
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 580.0+ bytes

In [9]:
df_bookings['channel'] = df_bookings.channel.astype("category")

In [10]:
df_bookings['status'] = df_bookings.status.astype("category")

In [11]:
df_cities['country'] = df_cities['country'].astype("category")

In [12]:
df_hotels['hotel_name'] = df_hotels['hotel_name'].astype("category")

In [13]:
df_hotels['category'] = df_hotels['category'].astype("category")

In [14]:
df_bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   booking_id     1001 non-null   int64
 1   hotel_id       1001 non-null   int64
 2   booking_date   1001 non-null   datetime64[ns]
 3   check_in_date  1001 non-null   datetime64[ns]
 4   room_nights    1000 non-null   float64
 5   guests         1001 non-null   int64
 6   channel        1001 non-null   category
 7   status         1001 non-null   category
 8   amount_gbp     1000 non-null   float64
dtypes: category(2), datetime64[ns](2), float64(2), int64(3)
memory usage: 57.2 KB

In [15]:
df_bookings.isna().sum()

booking_id       0
hotel_id         0
booking_date     0
check_in_date    0
room_nights      1
guests           0
channel          0
status           0
amount_gbp       1
dtype: int64

In [16]:
df_bookings.room_nights.isna().sum()/len(df_bookings.room_nights)*100

np.float64(0.0999000999000999)

In [17]:
df_daily_finance.isna().sum()

date                    3
hotel_id                0
revenue_gbp             4
room_revenue_gbp        0
food_revenue_gbp        0
operating_cost_gbp      2
occupancy_pct           0
rating                  3
notes                 362
dtype: int64

In [18]:
#total missing values 
df_daily_finance.isna().sum().sum()

np.int64(374)

In [19]:
#percentage for date
df_daily_finance.date.isna().sum()/df_daily_finance.shape[0]*100

np.float64(0.41551246537396125)

In [20]:
#percentage for revenue_gbp
df_daily_finance.revenue_gbp.isna().sum()/len(df_daily_finance.revenue_gbp)*100

np.float64(0.554016620498615)

In [21]:
#percentage for operating_cost_gbp
df_daily_finance.operating_cost_gbp.isna().sum()/len(df_daily_finance.operating_cost_gbp)* 100

np.float64(0.2770083102493075)

In [22]:
#percentage for rating
df_daily_finance.rating.isna().sum()/len(df_daily_finance.rating)*100

np.float64(0.41551246537396125)

In [23]:
#percentage for notes
df_daily_finance.notes.isna().sum()/len(df_daily_finance.notes)*100

np.float64(50.13850415512465)

In [24]:
df_campaigns.isna().sum()

campaign_id      0
city_id          0
campaign_name    0
start_date       0
end_date         0
budget_gbp       0
channel          0
dtype: int64

In [25]:
df_bookings.duplicated().sum()

np.int64(1)

In [26]:
df_bookings[df_bookings.duplicated(keep=False)]

,booking_id,hotel_id,booking_date,check_in_date,room_nights,guests,channel,status,amount_gbp
500,10501,104,2026-01-26,2026-02-14,3.0,2,Travel Agent,Cancelled,0.0
1000,10501,104,2026-01-26,2026-02-14,3.0,2,Travel Agent,Cancelled,0.0

In [27]:
df_bookings.duplicated().sum()/df_bookings.shape[0]*100

np.float64(0.0999000999000999)

In [28]:
df_bookings.drop_duplicates(inplace=True)

In [29]:
df_bookings.duplicated().sum()

np.int64(0)

In [30]:
df_daily_finance.duplicated().sum()

np.int64(2)

In [31]:
df_daily_finance[df_daily_finance.duplicated(keep=False)]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
119,2026-01-15,108,18916.57,13016.98,5899.59,14740.27,67.7,4.0,promotion
349,2026-02-13,106,13789.95,9293.66,4496.29,9708.98,52.1,4.4,NaN
720,2026-01-15,108,18916.57,13016.98,5899.59,14740.27,67.7,4.0,promotion
721,2026-02-13,106,13789.95,9293.66,4496.29,9708.98,52.1,4.4,NaN

In [32]:
df_daily_finance[df_daily_finance.duplicated(keep=False)]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
119,2026-01-15,108,18916.57,13016.98,5899.59,14740.27,67.7,4.0,promotion
349,2026-02-13,106,13789.95,9293.66,4496.29,9708.98,52.1,4.4,NaN
720,2026-01-15,108,18916.57,13016.98,5899.59,14740.27,67.7,4.0,promotion
721,2026-02-13,106,13789.95,9293.66,4496.29,9708.98,52.1,4.4,NaN

In [33]:
df_daily_finance.drop_duplicates(inplace=True)

In [34]:
df_daily_finance

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
0,2026-01-01,101,12969.00,8502.30,4466.70,9344.90,57.2,3.7,NaN
1,2026-01-01,102,13771.00,10241.40,3529.60,9301.41,63.3,3.5,NaN
2,2026-01-01,103,12545.00,8437.42,4107.58,8636.78,55.4,4.5,maintenance
3,2026-01-01,104,14532.00,10153.98,4378.02,9494.02,56.2,4.7,NaN
4,2026-01-01,105,15809.00,11053.12,4755.88,9705.31,57.7,4.6,NaN
...,...,...,...,...,...,...,...,...,...
715,2026-03-31,104,17751.77,11818.09,5933.68,10041.83,72.7,4.1,conference
716,2026-03-31,105,16205.43,10580.08,5625.35,9737.45,59.2,4.0,NaN
717,2026-03-31,106,16476.09,11048.57,5427.52,11914.04,62.8,4.9,maintenance
718,2026-03-31,107,16030.75,10517.15,5513.60,10092.67,53.8,4.4,conference
719,2026-03-31,108,17713.41,13714.53,3998.88,12523.15,59.2,4.8,NaN

In [35]:
#Question 1
df_daily_finance[df_daily_finance.revenue_gbp.isna()]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
54,2026-01-07,107,NaN,11873.64,4161.73,9570.35,60.1,3.9,promotion
179,2026-01-23,104,NaN,10984.39,3346.63,10012.49,55.9,4.1,conference
332,2026-02-11,105,NaN,10700.44,3774.80,8959.48,62.0,4.0,maintenance
599,2026-03-16,108,NaN,10676.60,5724.42,11597.47,52.0,4.7,NaN

In [36]:
#Question 2
df_daily_finance[df_daily_finance.operating_cost_gbp.isna()]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
96,2026-01-13,101,14542.86,9643.46,4899.40,NaN,61.6,4.4,NaN
286,2026-02-05,107,18464.56,13878.35,4586.21,NaN,61.0,4.1,promotion

In [37]:
#Question 3
df_daily_finance[df_daily_finance.rating.isna()]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
124,2026-01-16,105,14815.70,11502.93,3312.77,10034.27,61.4,NaN,promotion
454,2026-02-26,107,14375.01,9503.38,4871.63,11204.91,51.0,NaN,NaN
689,2026-03-28,102,14894.96,11465.06,3429.90,11061.25,67.8,NaN,promotion

In [38]:
#Question 4
len(df_daily_finance['date'][df_daily_finance['notes'].notna()])

359

In [39]:
#Question 5
df_daily_finance[df_daily_finance.occupancy_pct < 50]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
5,2026-01-01,106,13979.00,9690.10,4288.90,8842.63,49.8,3.9,NaN
38,2026-01-05,107,15087.18,11033.26,4053.92,10173.82,46.4,3.6,NaN
42,2026-01-06,103,12937.21,8623.76,4313.45,7763.25,48.9,4.5,NaN
200,2026-01-26,101,12070.65,8842.33,3228.32,6710.43,49.9,4.6,NaN
274,2026-02-04,103,13129.69,9723.80,3405.89,8100.92,48.7,4.0,conference
...,...,...,...,...,...,...,...,...,...
652,2026-03-23,105,13945.58,10084.74,3860.84,7823.90,48.5,4.7,NaN
654,2026-03-23,107,15743.78,10528.96,5214.82,11142.19,48.9,4.1,NaN
664,2026-03-25,101,11252.07,8543.47,2708.60,7905.39,49.1,4.0,promotion
668,2026-03-25,105,14237.76,11068.71,3169.05,10595.75,49.6,4.8,promotion
680,2026-03-27,101,11882.06,9235.85,2646.21,8571.78,49.2,4.1,NaN

In [40]:
df_daily_finance[df_daily_finance.occupancy_pct < 50].groupby('hotel_id')['hotel_id'].count().sort_values(ascending=False)

hotel_id
108    13
103    12
107    11
102    11
106     8
105     8
104     6
101     5
Name: hotel_id, dtype: int64

In [41]:
#Question 6
df_daily_finance[df_daily_finance.revenue_gbp>18000]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
7,2026-01-01,108,18297.00,13320.39,4976.61,13789.61,62.2,3.8,NaN
20,2026-01-03,105,18743.49,14317.60,4425.89,13545.96,78.3,4.0,NaN
21,2026-01-03,106,18513.76,12258.74,6255.02,10196.39,74.0,4.5,conference
22,2026-01-03,107,20636.03,13723.19,6912.84,15681.41,82.3,3.9,maintenance
23,2026-01-03,108,20377.30,14778.76,5598.54,11923.84,76.9,4.3,conference
...,...,...,...,...,...,...,...,...,...
700,2026-03-29,105,21185.09,15537.19,5647.90,13685.99,87.7,4.7,NaN
701,2026-03-29,106,21760.84,16508.26,5252.58,16014.02,83.8,3.5,NaN
702,2026-03-29,107,19226.60,14109.16,5117.44,11458.62,74.7,3.7,NaN
703,2026-03-29,108,22651.36,15291.45,7359.91,16831.27,84.9,3.9,conference
711,2026-03-30,108,18183.46,11740.86,6442.60,11168.21,60.2,3.7,NaN

In [42]:
df_daily_finance[df_daily_finance.revenue_gbp>18000].groupby("hotel_id")['hotel_id'].count().sort_values(ascending=False)

hotel_id
108    44
107    28
106    25
105    18
104    10
103     3
101     1
Name: hotel_id, dtype: int64

In [43]:
#Question 7
df_daily_finance[df_daily_finance.rating>=4.5]['date'].count()

np.int64(240)

In [44]:
#Question 8
df_daily_finance[(df_daily_finance.revenue_gbp>18000 ) & (df_daily_finance.occupancy_pct>70)]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
20,2026-01-03,105,18743.49,14317.60,4425.89,13545.96,78.3,4.0,NaN
21,2026-01-03,106,18513.76,12258.74,6255.02,10196.39,74.0,4.5,conference
22,2026-01-03,107,20636.03,13723.19,6912.84,15681.41,82.3,3.9,maintenance
23,2026-01-03,108,20377.30,14778.76,5598.54,11923.84,76.9,4.3,conference
27,2026-01-04,104,19209.96,13773.01,5436.95,11736.58,84.4,4.1,NaN
...,...,...,...,...,...,...,...,...,...
699,2026-03-29,104,19089.33,13078.74,6010.59,11005.82,75.6,4.2,conference
700,2026-03-29,105,21185.09,15537.19,5647.90,13685.99,87.7,4.7,NaN
701,2026-03-29,106,21760.84,16508.26,5252.58,16014.02,83.8,3.5,NaN
702,2026-03-29,107,19226.60,14109.16,5117.44,11458.62,74.7,3.7,NaN
703,2026-03-29,108,22651.36,15291.45,7359.91,16831.27,84.9,3.9,conference

In [45]:
#Question 9
df_daily_finance[(df_daily_finance.rating < 4) & (df_daily_finance.occupancy_pct>80)]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
22,2026-01-03,107,20636.03,13723.19,6912.84,15681.41,82.3,3.9,maintenance
196,2026-01-25,105,20218.16,13540.00,6678.16,14093.74,87.4,3.6,NaN
253,2026-02-01,106,20922.11,16164.32,4757.79,16305.60,86.7,3.6,maintenance
255,2026-02-01,108,23039.62,17216.63,5822.99,13689.25,91.4,3.7,NaN
308,2026-02-08,105,19432.64,14996.68,4435.96,14687.83,82.3,3.9,maintenance
511,2026-03-05,108,15583.70,10120.91,5462.79,9510.77,108.0,3.6,promotion
639,2026-03-21,108,20281.16,15782.94,4498.22,15319.46,80.1,3.7,maintenance
694,2026-03-28,107,20609.67,16016.40,4593.27,15676.94,80.4,3.9,NaN
701,2026-03-29,106,21760.84,16508.26,5252.58,16014.02,83.8,3.5,NaN
703,2026-03-29,108,22651.36,15291.45,7359.91,16831.27,84.9,3.9,conference

In [46]:
#Question 10
df_daily_finance[df_daily_finance['notes'].str.contains('promotion',case=False, na=False)].shape[0]

117

In [47]:
# Bonus challange
df_daily_finance[(df_daily_finance.revenue_gbp >15000) & (df_daily_finance.revenue_gbp <18000)]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
4,2026-01-01,105,15809.00,11053.12,4755.88,9705.31,57.7,4.6,NaN
6,2026-01-01,107,17238.00,12141.06,5096.94,9975.80,69.5,3.6,NaN
12,2026-01-02,105,15915.33,11426.78,4488.55,11259.48,68.1,4.6,NaN
13,2026-01-02,106,17119.82,11033.62,6086.20,10658.02,61.2,3.8,conference
14,2026-01-02,107,17999.31,13328.63,4670.68,10779.86,65.8,4.7,maintenance
...,...,...,...,...,...,...,...,...,...
715,2026-03-31,104,17751.77,11818.09,5933.68,10041.83,72.7,4.1,conference
716,2026-03-31,105,16205.43,10580.08,5625.35,9737.45,59.2,4.0,NaN
717,2026-03-31,106,16476.09,11048.57,5427.52,11914.04,62.8,4.9,maintenance
718,2026-03-31,107,16030.75,10517.15,5513.60,10092.67,53.8,4.4,conference
719,2026-03-31,108,17713.41,13714.53,3998.88,12523.15,59.2,4.8,NaN

In [48]:
df_daily_finance[(df_daily_finance.revenue_gbp >15000) & (df_daily_finance.revenue_gbp <18000)]['revenue_gbp'].max()

17999.31

In [49]:
df_daily_finance[(df_daily_finance.revenue_gbp >15000) & (df_daily_finance.revenue_gbp <18000)]['revenue_gbp'].min()

15001.94

In [50]:
mean_occupancy=df_daily_finance.groupby('hotel_id')['occupancy_pct'].mean()

In [51]:
hotel_with_highest_occ = mean_occupancy.idxmax()

In [52]:
df_daily_finance.groupby('hotel_id')['revenue_gbp'].mean().idxmax()

np.int64(108)

In [53]:
df_daily_finance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 720 entries, 0 to 719
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                717 non-null    datetime64[ns]
 1   hotel_id            720 non-null    int64
 2   revenue_gbp         716 non-null    float64
 3   room_revenue_gbp    720 non-null    float64
 4   food_revenue_gbp    720 non-null    float64
 5   operating_cost_gbp  718 non-null    float64
 6   occupancy_pct       720 non-null    float64
 7   rating              717 non-null    float64
 8   notes               359 non-null    object
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 56.2+ KB

In [54]:
# revenue_gbp
df_daily_finance['revenue_gbp'].count()
df_daily_finance['revenue_gbp'].mean()
df_daily_finance['revenue_gbp'].median()
df_daily_finance['revenue_gbp'].std()
df_daily_finance['revenue_gbp'].min()
df_daily_finance['revenue_gbp'].max()
df_daily_finance['revenue_gbp'].quantile(0.25)
df_daily_finance['revenue_gbp'].quantile(0.75)
# room_revenue_gbp   
df_daily_finance.room_revenue_gbp.count()
df_daily_finance.room_revenue_gbp.mean()
df_daily_finance.room_revenue_gbp.median()
df_daily_finance.room_revenue_gbp.std()
df_daily_finance.room_revenue_gbp.min()
df_daily_finance.room_revenue_gbp.max()
df_daily_finance.room_revenue_gbp.quantile(0.25)
df_daily_finance.room_revenue_gbp.quantile(0.75)
# food_revenue_gbp 
df_daily_finance.food_revenue_gbp.count()
df_daily_finance.food_revenue_gbp.mean()
df_daily_finance.food_revenue_gbp.median()
df_daily_finance.food_revenue_gbp.std()
df_daily_finance.food_revenue_gbp.min()
df_daily_finance.food_revenue_gbp.max()
df_daily_finance.food_revenue_gbp.quantile(0.25)
df_daily_finance.food_revenue_gbp.quantile(0.75)
# operating_cost_gbp
df_daily_finance.operating_cost_gbp.count()
df_daily_finance.operating_cost_gbp.mean()
df_daily_finance.operating_cost_gbp.median()
df_daily_finance.operating_cost_gbp.std()
df_daily_finance.operating_cost_gbp.min()
df_daily_finance.operating_cost_gbp.max()
df_daily_finance.operating_cost_gbp.quantile(0.25)
df_daily_finance.operating_cost_gbp.quantile(0.75)
# ccupancy_pct  
df_daily_finance.occupancy_pct.count()
df_daily_finance.occupancy_pct.mean()
df_daily_finance.occupancy_pct.median()
df_daily_finance.occupancy_pct.std()
df_daily_finance.occupancy_pct.min()
df_daily_finance.occupancy_pct.max()
df_daily_finance.occupancy_pct.quantile(0.25)
df_daily_finance.occupancy_pct.quantile(0.75)
# rating 
df_daily_finance.rating.count()
df_daily_finance.rating.mean()
df_daily_finance.rating.median()
df_daily_finance.rating.std()
df_daily_finance.rating.min()
df_daily_finance.rating.max()
df_daily_finance.rating.quantile(0.25)
df_daily_finance.rating.quantile(0.75)

np.float64(4.6)

In [55]:
df_daily_finance.describe()

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating
count,717,720.000000,716.000000,720.000000,720.000000,718.000000,720.000000,717.000000
mean,2026-02-14 13:47:26.861924608,104.500000,15545.203953,11033.310403,4510.590542,10380.515292,62.514444,4.226918
min,2026-01-01 00:00:00,101.000000,9251.870000,6434.560000,2381.630000,5498.530000,-4.000000,3.500000
25%,2026-01-23 00:00:00,102.750000,13671.292500,9647.277500,3753.152500,8800.370000,55.575000,3.900000
50%,2026-02-15 00:00:00,104.500000,15341.225000,10946.010000,4458.420000,10103.375000,62.200000,4.200000
75%,2026-03-09 00:00:00,106.250000,17309.222500,12261.750000,5166.740000,11724.025000,68.725000,4.600000
max,2026-03-31 00:00:00,108.000000,24211.690000,17870.850000,8406.930000,18436.120000,108.000000,4.900000
std,NaN,2.292881,2639.612702,1999.064685,989.884037,2129.565076,10.161698,0.398058

In [56]:
df_daily_finance.operating_cost_gbp.max()-df_daily_finance.operating_cost_gbp.min()

12937.59

In [57]:
df_daily_finance[df_daily_finance.revenue_gbp==df_daily_finance.revenue_gbp.min()]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
496,2026-03-04,101,9251.87,6434.56,2817.31,5738.63,49.6,3.8,maintenance

In [58]:
df_daily_finance.groupby('hotel_id')['rating'].mean().idxmax()

np.int64(103)

In [59]:
df_daily_finance[df_daily_finance.revenue_gbp==df_daily_finance['revenue_gbp'].min()]

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
496,2026-03-04,101,9251.87,6434.56,2817.31,5738.63,49.6,3.8,maintenance

In [60]:
df_daily_finance.describe().T

,count,mean,min,25%,50%,75%,max,std
date,717,2026-02-14 13:47:26.861924608,2026-01-01 00:00:00,2026-01-23 00:00:00,2026-02-15 00:00:00,2026-03-09 00:00:00,2026-03-31 00:00:00,NaN
hotel_id,720.0,104.5,101.0,102.75,104.5,106.25,108.0,2.292881
revenue_gbp,716.0,15545.203953,9251.87,13671.2925,15341.225,17309.2225,24211.69,2639.612702
room_revenue_gbp,720.0,11033.310403,6434.56,9647.2775,10946.01,12261.75,17870.85,1999.064685
food_revenue_gbp,720.0,4510.590542,2381.63,3753.1525,4458.42,5166.74,8406.93,989.884037
operating_cost_gbp,718.0,10380.515292,5498.53,8800.37,10103.375,11724.025,18436.12,2129.565076
occupancy_pct,720.0,62.514444,-4.0,55.575,62.2,68.725,108.0,10.161698
rating,717.0,4.226918,3.5,3.9,4.2,4.6,4.9,0.398058

In [61]:
(df_daily_finance.groupby('hotel_id')['revenue_gbp'].mean()-df_daily_finance.groupby('hotel_id')['operating_cost_gbp'].mean()).idxmax()

np.int64(108)

In [62]:
df_daily_finance.describe().round(2).T

,count,mean,min,25%,50%,75%,max,std
date,717,2026-02-14 13:47:26.861924608,2026-01-01 00:00:00,2026-01-23 00:00:00,2026-02-15 00:00:00,2026-03-09 00:00:00,2026-03-31 00:00:00,NaN
hotel_id,720.0,104.5,101.0,102.75,104.5,106.25,108.0,2.29
revenue_gbp,716.0,15545.2,9251.87,13671.29,15341.22,17309.22,24211.69,2639.61
room_revenue_gbp,720.0,11033.31,6434.56,9647.28,10946.01,12261.75,17870.85,1999.06
food_revenue_gbp,720.0,4510.59,2381.63,3753.15,4458.42,5166.74,8406.93,989.88
operating_cost_gbp,718.0,10380.52,5498.53,8800.37,10103.38,11724.02,18436.12,2129.57
occupancy_pct,720.0,62.51,-4.0,55.58,62.2,68.72,108.0,10.16
rating,717.0,4.23,3.5,3.9,4.2,4.6,4.9,0.4

In [63]:
df_hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hotel_id     8 non-null      int64
 1   hotel_name   8 non-null      category
 2   city_id      8 non-null      int64
 3   category     8 non-null      category
 4   rooms        8 non-null      int64
 5   opened_date  8 non-null      datetime64[ns]
 6   manager      8 non-null      object
dtypes: category(2), datetime64[ns](1), int64(3), object(1)
memory usage: 1.0+ KB

In [64]:
df_daily_finance.shape

(720, 9)

In [65]:
df_hotel_finance = df_daily_finance.merge(df_hotels, on='hotel_id')

In [66]:
df_hotel_finance.shape

(720, 15)

In [67]:
df_hotel_finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                717 non-null    datetime64[ns]
 1   hotel_id            720 non-null    int64
 2   revenue_gbp         716 non-null    float64
 3   room_revenue_gbp    720 non-null    float64
 4   food_revenue_gbp    720 non-null    float64
 5   operating_cost_gbp  718 non-null    float64
 6   occupancy_pct       720 non-null    float64
 7   rating              717 non-null    float64
 8   notes               359 non-null    object
 9   hotel_name          720 non-null    category
 10  city_id             720 non-null    int64
 11  category            720 non-null    category
 12  rooms               720 non-null    int64
 13  opened_date         720 non-null    datetime64[ns]
 14  manager             720 non-null    object
dtypes: category(2), datetime64[ns](2), float64(6), int64(3), object(2)
memory usage: 75.2+ KB

In [68]:
df_hotel_finance.loc[df_hotel_finance.revenue_gbp==df_hotel_finance.revenue_gbp.max(),['hotel_id','hotel_name','revenue_gbp']]

     hotel_id           hotel_name  revenue_gbp
143       108  Sofia Airport Hotel     24211.69

In [69]:
df_hotel_finance.groupby('category')['revenue_gbp'].mean().idxmax()

/tmp/ipykernel_22048/598889539.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hotel_finance.groupby('category')['revenue_gbp'].mean().idxmax()

'Business'

In [70]:
df_hotel_finance.loc[df_hotel_finance.revenue_gbp==df_hotel_finance['revenue_gbp'].max(),['manager']]

           manager
143  Anna Nikolova

In [71]:
g = df_hotel_finance[['hotel_name','manager','occupancy_pct']].groupby(['hotel_name','manager'],observed=True, as_index=False)['occupancy_pct'].mean()

In [72]:
g

                hotel_name            manager  occupancy_pct
0    Bansko Mountain Lodge      Petar Marinov      61.838889
1            Burgas Marina   Nikolay Dimitrov      63.014444
2      Grand Sofia Central      Elena Petrova      62.084444
3        Plovdiv Riverside      Ivan Georgiev      61.983333
4        Ruse Danube Plaza    Georgi Stoyanov      62.790000
5      Sofia Airport Hotel      Anna Nikolova      63.720000
6           Varna Sea View       Maria Koleva      61.448889
7  Veliko Tarnovo Heritage  Desislava Ivanova      63.235556

In [73]:
g[g['occupancy_pct']==g.occupancy_pct.max()]

            hotel_name        manager  occupancy_pct
5  Sofia Airport Hotel  Anna Nikolova          63.72

In [74]:
df_cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city_id     8 non-null      int64
 1   city        8 non-null      object
 2   region      8 non-null      object
 3   country     8 non-null      category
 4   population  8 non-null      int64
dtypes: category(1), int64(2), object(2)
memory usage: 512.0+ bytes

In [75]:
df_hotel_finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                717 non-null    datetime64[ns]
 1   hotel_id            720 non-null    int64
 2   revenue_gbp         716 non-null    float64
 3   room_revenue_gbp    720 non-null    float64
 4   food_revenue_gbp    720 non-null    float64
 5   operating_cost_gbp  718 non-null    float64
 6   occupancy_pct       720 non-null    float64
 7   rating              717 non-null    float64
 8   notes               359 non-null    object
 9   hotel_name          720 non-null    category
 10  city_id             720 non-null    int64
 11  category            720 non-null    category
 12  rooms               720 non-null    int64
 13  opened_date         720 non-null    datetime64[ns]
 14  manager             720 non-null    object
dtypes: category(2), datetime64[ns](2), float64(6), int64(3), object(2)
memory usage: 75.2+ KB

In [76]:
df_hotel_finance_cities = pd.merge(left=df_hotel_finance,right=df_cities, on='city_id')

In [77]:
df_hotel_finance_cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                717 non-null    datetime64[ns]
 1   hotel_id            720 non-null    int64
 2   revenue_gbp         716 non-null    float64
 3   room_revenue_gbp    720 non-null    float64
 4   food_revenue_gbp    720 non-null    float64
 5   operating_cost_gbp  718 non-null    float64
 6   occupancy_pct       720 non-null    float64
 7   rating              717 non-null    float64
 8   notes               359 non-null    object
 9   hotel_name          720 non-null    category
 10  city_id             720 non-null    int64
 11  category            720 non-null    category
 12  rooms               720 non-null    int64
 13  opened_date         720 non-null    datetime64[ns]
 14  manager             720 non-null    object
 15  city                720 non-null    object
 16  region              720 non-null    object
 17  country             720 non-null    category
 18  population          720 non-null    int64
dtypes: category(3), datetime64[ns](2), float64(6), int64(4), object(4)
memory usage: 92.9+ KB

In [78]:
g = df_hotel_finance_cities.groupby('city')['revenue_gbp'].max().reset_index()

In [79]:
g.loc[g['revenue_gbp']==g.revenue_gbp.max(),['city','revenue_gbp']]

    city  revenue_gbp
4  Sofia     24211.69

In [80]:
g

             city  revenue_gbp
0          Bansko     22867.90
1          Burgas     20710.53
2         Plovdiv     17531.99
3            Ruse     21890.79
4           Sofia     24211.69
5           Varna     18655.84
6  Veliko Tarnovo     21317.91

In [81]:
df_hotel_finance_cities['country'].value_counts()

country
Bulgaria    720
Name: count, dtype: int64

In [82]:
df_hotel_finance_cities.isnull().sum()

date                    3
hotel_id                0
revenue_gbp             4
room_revenue_gbp        0
food_revenue_gbp        0
operating_cost_gbp      2
occupancy_pct           0
rating                  3
notes                 361
hotel_name              0
city_id                 0
category                0
rooms                   0
opened_date             0
manager                 0
city                    0
region                  0
country                 0
population              0
dtype: int64

In [83]:
df_cities.isnull().sum()

city_id       0
city          0
region        0
country       0
population    0
dtype: int64

In [84]:
df_hotel_finance_cities.shape

(720, 19)

In [85]:
df_hotel_finance_cities.groupby('hotel_name')['revenue_gbp'].sum().sort_values(ascending=False).head(3)

/tmp/ipykernel_22048/2627034571.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hotel_finance_cities.groupby('hotel_name')['revenue_gbp'].sum().sort_values(ascending=False).head(3)

hotel_name
Sofia Airport Hotel      1608846.69
Bansko Mountain Lodge    1519543.02
Ruse Danube Plaza        1495728.06
Name: revenue_gbp, dtype: float64

In [86]:
df_hotel_finance = df_daily_finance.merge(
    df_hotels,
    on="hotel_id",
    how="left",
    validate="many_to_one"
)

In [87]:
sheets

['hotels', 'cities', 'daily_finance', 'bookings', 'campaigns']

In [90]:
df_campaigns.shape

(6, 7)

In [94]:
df_daily_finance

,date,hotel_id,revenue_gbp,room_revenue_gbp,food_revenue_gbp,operating_cost_gbp,occupancy_pct,rating,notes
0,2026-01-01,101,12969.00,8502.30,4466.70,9344.90,57.2,3.7,NaN
1,2026-01-01,102,13771.00,10241.40,3529.60,9301.41,63.3,3.5,NaN
2,2026-01-01,103,12545.00,8437.42,4107.58,8636.78,55.4,4.5,maintenance
3,2026-01-01,104,14532.00,10153.98,4378.02,9494.02,56.2,4.7,NaN
4,2026-01-01,105,15809.00,11053.12,4755.88,9705.31,57.7,4.6,NaN
...,...,...,...,...,...,...,...,...,...
715,2026-03-31,104,17751.77,11818.09,5933.68,10041.83,72.7,4.1,conference
716,2026-03-31,105,16205.43,10580.08,5625.35,9737.45,59.2,4.0,NaN
717,2026-03-31,106,16476.09,11048.57,5427.52,11914.04,62.8,4.9,maintenance
718,2026-03-31,107,16030.75,10517.15,5513.60,10092.67,53.8,4.4,conference
719,2026-03-31,108,17713.41,13714.53,3998.88,12523.15,59.2,4.8,NaN

In [96]:
df_hotel_finance_cities.describe().T

,count,mean,min,25%,50%,75%,max,std
date,717,2026-02-14 13:47:26.861924608,2026-01-01 00:00:00,2026-01-23 00:00:00,2026-02-15 00:00:00,2026-03-09 00:00:00,2026-03-31 00:00:00,NaN
hotel_id,720.0,104.5,101.0,102.75,104.5,106.25,108.0,2.292881
revenue_gbp,716.0,15545.203953,9251.87,13671.2925,15341.225,17309.2225,24211.69,2639.612702
room_revenue_gbp,720.0,11033.310403,6434.56,9647.2775,10946.01,12261.75,17870.85,1999.064685
food_revenue_gbp,720.0,4510.590542,2381.63,3753.1525,4458.42,5166.74,8406.93,989.884037
operating_cost_gbp,718.0,10380.515292,5498.53,8800.37,10103.375,11724.025,18436.12,2129.565076
occupancy_pct,720.0,62.514444,-4.0,55.575,62.2,68.725,108.0,10.161698
rating,717.0,4.226918,3.5,3.9,4.2,4.6,4.9,0.398058
city_id,720.0,3.625,1.0,1.75,3.5,5.25,7.0,2.119106
rooms,720.0,151.875,75.0,121.25,152.5,185.0,220.0,45.096385
opened_date,720,2016-01-06 18:00:00,2010-06-05 00:00:00,2014-04-11 18:00:00,2016-01-19 00:00:00,2018-10-25 18:00:00,2020-02-15 00:00:00,NaN
population,720.0,460000.0,9000.0,124250.0,272500.0,578750.0,1286000.0,489461.683808

In [104]:
df_hotel_finance_cities.groupby('hotel_name')['rating'].mean().sort_values(ascending=False)

/tmp/ipykernel_22048/708036641.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_hotel_finance_cities.groupby('hotel_name')['rating'].mean().sort_values(ascending=False)

hotel_name
Varna Sea View             4.245556
Ruse Danube Plaza          4.242222
Burgas Marina              4.237778
Bansko Mountain Lodge      4.235955
Sofia Airport Hotel        4.227778
Plovdiv Riverside          4.213483
Veliko Tarnovo Heritage    4.208989
Grand Sofia Central        4.203333
Name: rating, dtype: float64